name: LoginPlugin
version: 1.0
main: me.twojplugin.Main
api-version: 1.21

commands:
  register:
    description: Zarejestruj nowe konto
    usage: /register <hasło> <powtórz>
  login:
    description: Zaloguj się do konta
    usage: /login <hasło>
  zmienhaslo:
    description: Zmień swoje hasło
    usage: /zmienhaslo <stare> <nowe> <powtórz>
  jzmienhaslo:
    description: Admin zmienia hasło
    usage: /jzmienhaslo <nick> <nowe_hasło>
  unregister:
    description: Usuń konto gracza (OP)
    usage: /unregister <nick>
  premium:
    description: Dodaj premium autologowanie
    usage: /premium <nick>
  unpremium:
    description: Odejmij premium autologowanie
    usage: /unpremium <nick>
  lastlogin:
    description: Pokaż daty rejestracji/wejścia/wyjścia
    usage: /lastlogin [nick]
  loginhelp:
    description: Pomoc pluginu
    usage: /loginhelp
